/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package v_quizjava;

import c_quizjava.QuizLogic;
import java.awt.Color;
import javax.swing.JCheckBox;
import m_quizjava.Question;

/**
 *
 * @author Mikołaj
 */
public class QuizFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    QuizLogic quizLogic;
    javax.swing.JCheckBox[] answerCheckbox;
    
    public QuizFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        quizLogic = new QuizLogic();
        initCheckbox();
        loadQuestion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionTextArea = new javax.swing.JTextArea();
        checkButton = new javax.swing.JButton();
        answer1Checkbox = new javax.swing.JCheckBox();
        answer2Checkbox = new javax.swing.JCheckBox();
        answer3Checkbox = new javax.swing.JCheckBox();
        answer4Checkbox = new javax.swing.JCheckBox();
        returnButton = new javax.swing.JButton();
        quizLabel = new javax.swing.JLabel();
        questionNumberToBeEditedLabel = new javax.swing.JLabel();
        answer5Checkbox = new javax.swing.JCheckBox();
        answer6Checkbox = new javax.swing.JCheckBox();
        nextQuestionButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        questionTextArea.setEditable(false);
        questionTextArea.setColumns(20);
        questionTextArea.setRows(5);
        jScrollPane1.setViewportView(questionTextArea);

        checkButton.setText("Sprawdź");
        checkButton.setActionCommand("checkButton");
        checkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkButtonMouseClicked(evt);
            }
        });

        answer1Checkbox.setText("jCheckBox1");
        answer1Checkbox.setActionCommand("answer1Checkbox");

        answer2Checkbox.setText("jCheckBox2");
        answer2Checkbox.setToolTipText("");
        answer2Checkbox.setActionCommand("answer2Checkbox");

        answer3Checkbox.setText("jCheckBox3");
        answer3Checkbox.setActionCommand("answer3Checkbox");

        answer4Checkbox.setText("jCheckBox4");
        answer4Checkbox.setActionCommand("answer4Checkbox");

        returnButton.setText("Powrót do Menu");
        returnButton.setActionCommand("returnButton");
        returnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonMouseClicked(evt);
            }
        });

        quizLabel.setText("Quiz");

        questionNumberLabel.setText("Pytanie numer: ");

        questionNumberToBeEditedLabel.setText("0");

        answer5Checkbox.setText("jCheckBox5");
        answer5Checkbox.setActionCommand("answer5Checkbox");

        answer6Checkbox.setText("jCheckBox6");
        answer6Checkbox.setActionCommand("answer6Checkbox");

        nextQuestionButton.setText("NowePytanie");
        nextQuestionButton.setActionCommand("nextQuestionButton");
        nextQuestionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextQuestionButtonMouseClicked(evt);
            }
        });

        resultLabel.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        resultLabel.setText("Brawo!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(answer6Checkbox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(answer5Checkbox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(answer4Checkbox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(answer3Checkbox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(answer2Checkbox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nextQuestionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(answer1Checkbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(130, 130, 130)))
                        .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quizLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(questionNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(questionNumberToBeEditedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questionNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionNumberToBeEditedLabel)
                    .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer1Checkbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answer2Checkbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answer3Checkbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(answer4Checkbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(answer5Checkbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(answer6Checkbox))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextQuestionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkButtonMouseClicked
        // TODO add your handling code here:
        checkQuestion();
    }//GEN-LAST:event_checkButtonMouseClicked

    private void returnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_returnButtonMouseClicked

    private void nextQuestionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextQuestionButtonMouseClicked
        // TODO add your handling code here:
        loadQuestion();
    }//GEN-LAST:event_nextQuestionButtonMouseClicked

    private void initCheckbox()
    {
        answerCheckbox = new javax.swing.JCheckBox[] { answer1Checkbox,answer2Checkbox,answer3Checkbox,
            answer4Checkbox,answer5Checkbox,answer6Checkbox };
    }
    
    private void checkQuestion()
    {   
        Question question = quizLogic
                .getQuestionManager()
                .getQuestionByID(Integer.parseInt(questionNumberToBeEditedLabel.getText()));
        checkAnswers(question);
    }
    
    private void checkAnswers(Question question)
    {
        boolean result = true;
        for(int i=0; i<answerCheckbox.length; i++)
        {
            if(answerCheckbox[i].isSelected() || question.getAnswer(i).isCorrect())
            {
                if(/*answerCheckbox[i].isSelected() ==*/question.getAnswer(i).isCorrect())
                {
                    answerCheckbox[i].setForeground(Color.green);
                }
                else
                {
                    answerCheckbox[i].setForeground(Color.red);
                }
            }
            if(answerCheckbox[i].isSelected() != question.getAnswer(i).isCorrect())
            {
                result = false;
            }
        }
        setResultLabel(result);
    }
    
    private void resetColors()
    {
        for(int i=0; i<answerCheckbox.length; i++)
        {
            answerCheckbox[i].setForeground(Color.GRAY);
        }
    }
    
    private void resetSelection()
    {
        for(int i=0; i<answerCheckbox.length; i++)
        {
            answerCheckbox[i].setSelected(false);
        }
    }
    
    private void resetAnswers()
    {
        resetColors();
        resetSelection();
    }
    
    private void loadQuestion()
    {
        Question question = quizLogic.getQuestionManager().getRandomQuestion();
        setQuestionText(question);
        resetAnswers();
        resetResultLabel();
    }
    
    private void setResultLabel(boolean result)
    {
        if(result)
        {
            resultLabel.setText("Brawo!");
            resultLabel.setForeground(Color.green);
        }
        else
        {
            resultLabel.setText("Źle");
            resultLabel.setForeground(Color.red);
        }
    }
    
    private void resetResultLabel()
    {
        resultLabel.setText(null);
        resultLabel.setForeground(Color.gray);
    }
    
    private void setQuestionText(Question question)
    {
        questionNumberToBeEditedLabel.setText(String.valueOf(question.getQuestionID()));
        questionTextArea.setText(question.getQuestionString());
        for(int i=0; i<answerCheckbox.length; i++ )
        {
            answerCheckbox[i].setText(question.getAnswer(i).getAnswerString());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox answer1Checkbox;
    private javax.swing.JCheckBox answer2Checkbox;
    private javax.swing.JCheckBox answer3Checkbox;
    private javax.swing.JCheckBox answer4Checkbox;
    private javax.swing.JCheckBox answer5Checkbox;
    private javax.swing.JCheckBox answer6Checkbox;
    private javax.swing.JButton checkButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextQuestionButton;
    private final javax.swing.JLabel questionNumberLabel = new javax.swing.JLabel();
    private javax.swing.JLabel questionNumberToBeEditedLabel;
    private javax.swing.JTextArea questionTextArea;
    private javax.swing.JLabel quizLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JButton returnButton;
    // End of variables declaration//GEN-END:variables
}
